import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const schema=fs.readFileSync(new URL('../supabase/setup.sql',import.meta.url),'utf8');
const guest='11111111-1111-4111-8111-111111111111';
const stranger='22222222-2222-4222-8222-222222222222';
const staff='33333333-3333-4333-8333-333333333333';
await db.exec(`create role anon; create role authenticated;
create schema auth; create table auth.users(id uuid primary key,email text,is_anonymous boolean default false);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;
insert into auth.users values ('${guest}',null,true),('${stranger}',null,true),('${staff}','owner@example.com',false);`);
await db.exec(schema); await db.exec(schema); // Rerun must preserve data and work.
await db.exec(`insert into private.staff_members(user_id) values('${staff}');`);
const identity=async (id,role='authenticated')=>db.exec(`reset role; set role ${role}; select set_config('request.jwt.claim.sub','${id}',false);`);
const owner=async()=>db.exec('reset role');
const denied=async(promise,pattern)=>{let error;try{await promise;}catch(e){error=e;}assert.ok(error,'Expected operation to be rejected');if(pattern)assert.match(error.message,pattern);};
await identity('', 'anon');
assert.equal((await db.query('select * from public.products')).rows.length,6);
await denied(db.query('select * from public.orders'),/permission denied/);
await denied(db.query('select * from private.staff_members'),/permission denied/);
const picked=(await db.query("select id from public.products where slug='latte'")).rows[0].id;
const pickup=(await db.query("select to_timestamp(ceil(extract(epoch from now()+interval '16 minutes')/900)*900) as t")).rows[0].t;
const payload=JSON.stringify([{product_id:picked,style:'Hot',quantity:2,price_cents:1}]);
const call=(id,body=payload,time=pickup)=>db.query('select public.place_order($1,$2,$3,$4::jsonb) as result',[id,'Test Customer',time,body]);
await denied(call('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),/permission denied/);
await identity(guest);
const request='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const saved=(await call(request)).rows[0].result;
assert.equal(saved.total_cents,900,'Database ignores supplied fake prices');
assert.equal(saved.is_test,true);
assert.equal((await call(request)).rows[0].result.id,saved.id,'Retry returns same order');
assert.equal((await db.query('select count(*) as n from public.orders')).rows[0].n,1);
await denied(call(request,JSON.stringify([{product_id:picked,style:'Hot',quantity:1}])),/already used/);
await denied(db.query("insert into public.orders(customer_name) values('Bad')"),/permission denied/);
await denied(db.query("update public.orders set status='collected'"),/permission denied/);
await denied(db.query('select public.staff_set_order_status($1,$2)',[saved.id,'preparing']),/Staff access/);
await denied(call('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',JSON.stringify([{product_id:picked,style:'Impossible',quantity:1}])),/option is unavailable/);
await denied(call('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',JSON.stringify([{product_id:picked,style:'Hot',quantity:0}])),/quantity/);
await denied(call('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',JSON.stringify([{product_id:picked,style:'Hot',quantity:1}]),new Date().toISOString()),/pickup time/);
await denied(call('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',JSON.stringify([{product_id:picked,style:'Hot',quantity:1},{product_id:picked,style:'Hot',quantity:1}])),/duplicate/);
assert.equal((await db.query('select * from public.order_items')).rows.length,1);
await identity(stranger);
assert.equal((await db.query('select * from public.orders')).rows.length,0,'Other guests cannot read orders');
assert.equal((await db.query('select * from public.order_items')).rows.length,0,'Other guests cannot read line items');
assert.equal((await db.query('select public.is_staff() as yes')).rows[0].yes,false);
await identity(staff);
assert.equal((await db.query('select * from public.orders')).rows.length,1);
await denied(db.query('select public.staff_set_order_status($1,$2)',[saved.id,'collected']),/status changed/);
await db.query('select public.staff_set_order_status($1,$2)',[saved.id,'preparing']);
await db.query('select public.staff_set_order_status($1,$2)',[saved.id,'ready']);
await db.query('select public.staff_set_order_status($1,$2)',[saved.id,'collected']);
assert.equal((await db.query('select payment_status from public.orders')).rows[0].payment_status,'paid');
await db.query('select public.staff_set_product($1,$2,$3)',[picked,false,600]);
assert.equal((await db.query('select unit_price_cents from public.order_items')).rows[0].unit_price_cents,450,'Historical price is preserved');
await identity(guest);
await denied(call('cccccccc-cccc-4ccc-8ccc-cccccccccccc'),/unavailable/);
await identity(staff);await db.query('select public.staff_set_product($1,$2,$3)',[picked,true,600]);
await db.query('select public.staff_pause_orders(true)');await identity(guest);
await denied(call('cccccccc-cccc-4ccc-8ccc-cccccccccccc'),/paused/);
await identity(staff);await db.query('select public.staff_pause_orders(false)');
await owner();await db.exec('update public.store_settings set max_drinks_per_slot=2');
await identity(guest);await denied(call('cccccccc-cccc-4ccc-8ccc-cccccccccccc'),/slot is full/);
await owner();await db.exec('update public.store_settings set max_drinks_per_slot=20,testing_mode=false');
await identity(guest);await denied(call('cccccccc-cccc-4ccc-8ccc-cccccccccccc'),/Live ordering/);
await owner();await db.exec(`delete from private.staff_members where user_id='${staff}'`);
await identity(staff);await denied(db.query('select public.staff_pause_orders(true)'),/Staff access/);
console.log('PASS: schema reruns, RLS isolation, no direct writes, server pricing, idempotency, invalid options/quantities/times, staff allowlist and transitions, price snapshots, pause, capacity, test-only mode and revocation');
await db.close();
